### ISSUE TITLE
xychart-beta does not seem to support display

### ISSUE THREAD

**Issue by Howardnm** [FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin#1]
xychart-beta
    title "Sales Revenue"
    x-axis [jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec]
    y-axis "Revenue (in $)" 4000 --> 11000
    bar [5000, 6000, 7500, 8200, 9500, 10500, 11000, 10200, 9200, 8500, 7000, 6000]
    line [5000, 6000, 7500, 8200, 9500, 10500, 11000, 10200, 9200, 8500, 7000, 6000]

![image](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/assets/55622355/b6bbbfa8-983f-4c46-b137-38c4a1423489)

**Comment by FrancescoDiCursi** [comment]
Hi,
the plugin is made exclusively for flowcharts, not for xy chart. Did you open the issue on the wrong repository?

By the way I think I will implement it also for xy chart in future. What command did you use?

Thank you for using it!
